import type { APIRoute } from 'astro';
import { WP_URL, SITE_URL } from '../config';
import { getAllPostsForSitemap, getCategories } from '../lib/wp';

export const GET: APIRoute = async ({ params }) => {
  const sitemapParam = params.sitemap;
  if (!sitemapParam) {
    return new Response('Sitemap Not Specified', { status: 404 });
  }

  const wpBase = WP_URL.replace(/\/+$/, '');
  const siteUrl = SITE_URL.replace(/\/+$/, '');
  const siteHost = new URL(siteUrl).host;
  const fileName = `${sitemapParam}.xml`;

  // 1. Try to fetch the exact sitemap XML from WordPress / Rank Math
  try {
    const res = await fetch(`${wpBase}/${fileName}`, {
      headers: {
        'Accept': 'application/xml,text/xml,*/*',
        'User-Agent': 'TopNepali-Sitemap-Proxy/1.0',
      },
    });

    if (res.ok) {
      let xml = await res.text();
      // Ensure we received valid XML and not an HTML redirect/error page
      if (xml.includes('<?xml') && (xml.includes('<urlset') || xml.includes('<sitemapindex'))) {
        xml = xml
          .replace(/https?:\/\/wp\.topnepali\.com/gi, siteUrl)
          .replace(/\/\/wp\.topnepali\.com/gi, `//${siteHost}`);

        return new Response(xml, {
          status: 200,
          headers: {
            'Content-Type': 'application/xml; charset=utf-8',
            'Cache-Control': 'public, max-age=3600, s-maxage=86400, stale-while-revalidate=43200',
            'Cloudflare-CDN-Cache-Control': 'max-age=86400, stale-while-revalidate=43200',
          },
        });
      }
    }
  } catch (err) {
    console.error(`[sitemap] Error proxying ${fileName} from WordPress:`, err);
  }

  // 2. Intelligent Dynamic Fallback if WordPress redirects or is unavailable
  const now = new Date().toISOString().split('T')[0];

  if (sitemapParam.includes('category')) {
    const categories = await getCategories({ perPage: 100, hideEmpty: true });
    const entries = categories
      .map(
        (c) => `  <url>
    <loc>${siteUrl}/category/${c.slug}</loc>
    <lastmod>${now}</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
  </url>`
      )
      .join('\n');

    const xml = `<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="${siteUrl}/main-sitemap.xsl"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
<!-- XML Sitemap generated by TopNepali Headless Engine -->`;

    return new Response(xml, {
      status: 200,
      headers: {
        'Content-Type': 'application/xml; charset=utf-8',
        'Cache-Control': 'public, max-age=3600, s-maxage=86400',
      },
    });
  }

  if (sitemapParam.includes('page')) {
    const staticSlugs = [
      'blogs',
      'tools',
      'nepali-date-converter',
      'foreign-exchange-rates-for-nepali-currency',
      'nepali-calendar',
      'nepali-rashifal-horoscope',
      'about-us',
      'contact',
      'privacy',
      'terms-and-conditions',
    ];

    const entries = staticSlugs
      .map(
        (slug) => `  <url>
    <loc>${siteUrl}/${slug}</loc>
    <lastmod>${now}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>`
      )
      .join('\n');

    const xml = `<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="${siteUrl}/main-sitemap.xsl"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
<!-- XML Sitemap generated by TopNepali Headless Engine -->`;

    return new Response(xml, {
      status: 200,
      headers: {
        'Content-Type': 'application/xml; charset=utf-8',
        'Cache-Control': 'public, max-age=3600, s-maxage=86400',
      },
    });
  }

  if (sitemapParam.includes('post')) {
    const posts = await getAllPostsForSitemap();
    const entries = posts
      .map(
        (p) => `  <url>
    <loc>${siteUrl}/${p.slug}</loc>
    <lastmod>${p.lastmod || now}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.9</priority>
  </url>`
      )
      .join('\n');

    const xml = `<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="${siteUrl}/main-sitemap.xsl"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
<!-- XML Sitemap generated by TopNepali Headless Engine -->`;

    return new Response(xml, {
      status: 200,
      headers: {
        'Content-Type': 'application/xml; charset=utf-8',
        'Cache-Control': 'public, max-age=3600, s-maxage=86400',
      },
    });
  }

  return new Response(`Sitemap "${fileName}" could not be located.`, { status: 404 });
};
