import type { APIRoute } from 'astro';
import { WP_URL, SITE_URL } from '../config';

export const GET: APIRoute = async () => {
  const wpBase = WP_URL.replace(/\/+$/, '');
  const siteUrl = SITE_URL.replace(/\/+$/, '');
  const siteHost = new URL(siteUrl).host;

  // 1. Fetch Rank Math sitemap index from WordPress backend
  try {
    const res = await fetch(`${wpBase}/sitemap_index.xml`, {
      headers: {
        'Accept': 'application/xml,text/xml,*/*',
        'User-Agent': 'TopNepali-Sitemap-Proxy/1.0',
      },
    });

    if (res.ok) {
      let xml = await res.text();
      if (xml.includes('<sitemapindex')) {
        // Rewrite backend wp.topnepali.com domain to production topnepali.com
        xml = xml
          .replace(/https?:\/\/wp\.topnepali\.com/gi, siteUrl)
          .replace(/\/\/wp\.topnepali\.com/gi, `//${siteHost}`);

        return new Response(xml, {
          status: 200,
          headers: {
            'Content-Type': 'application/xml; charset=utf-8',
            'Cache-Control': 'public, max-age=3600, s-maxage=86400, stale-while-revalidate=43200',
            'Cloudflare-CDN-Cache-Control': 'max-age=86400, stale-while-revalidate=43200',
          },
        });
      }
    }
  } catch (err) {
    console.error('[sitemap_index] Failed to proxy from WordPress:', err);
  }

  // 2. Fallback sitemap index structure
  const now = new Date().toISOString();
  const fallback = `<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="${siteUrl}/main-sitemap.xsl"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
\t<sitemap>
\t\t<loc>${siteUrl}/post-sitemap1.xml</loc>
\t\t<lastmod>${now}</lastmod>
\t</sitemap>
\t<sitemap>
\t\t<loc>${siteUrl}/page-sitemap.xml</loc>
\t\t<lastmod>${now}</lastmod>
\t</sitemap>
\t<sitemap>
\t\t<loc>${siteUrl}/category-sitemap.xml</loc>
\t\t<lastmod>${now}</lastmod>
\t</sitemap>
</sitemapindex>
<!-- XML Sitemap generated by TopNepali Headless Engine -->`;

  return new Response(fallback, {
    status: 200,
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=1800, s-maxage=3600',
    },
  });
};
